services:
  chatterbox:
    image: chatterbox
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file: env/chatterbox.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 10s
      test: curl --fail http://localhost:8004 || exit 1
      timeout: 3s
    volumes:
      - chatterbox:/app
    restart: unless-stopped

  nginx:
    env_file: env/nginx.env
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 5s
      test: curl --fail http://localhost/ || exit 1
      timeout: 3s
    image: nginx:latest
    ports:
      - ${PORT:-4000}:80
    restart: unless-stopped
    volumes:
      - ./conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  chatterbox:
    external: false
